// src/components/FirstExample.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import anime from 'animejs';

	import Motion from 'svelte-motion/src/motion/MotionSSR.svelte';

	onMount(() => {
		anime({
			targets: '.element',
			translateX: 100,
			easing: 'spring',
			duration: 500
		});
	});
</script>

<div class="element" />

<Motion
	let:motion
	animate={{
		x: 100,
		transition: { type: 'spring', duration: 1, bounce: 0.6 },
		opacity: 1,
		scale: 1
	}}
>
	<div use:motion class="element-svelte-motion" />
</Motion>

<style lang="postcss">
	.element,
	.element-svelte-motion {
		@apply size-12 rounded-xl bg-yellow-400;
	}
</style>

// react/app/ui/examples/first-example.tsx
'use client';

import { motion } from "framer-motion";
import { useState } from "react";

export default function FirstExample() {

	return (
	  <div className="grid w-[100vh] h-[100vh] place-items-center bg-black">
		<motion.div className="size-12 bg-yellow-500 rounded-xl"  initial={{ opacity: 0, scale: 0 }}
  animate={{ opacity: 1, scale: 1 }} />
	  </div>
	)
  }
